# https://taskfile.dev

version: '3'

tasks:
  install:
    cmd: uv sync

  run:api:
    cmd: fastapi dev app/main.py

  run:cli:
    dir: packages/ocl
    cmd: uv run src/ocl/cli/app.py {{.CLI_ARGS}}

  run:lib:
    dir: packages/ocl
    cmd: uv run src/main.py
